name: Functions Validate

on:
  pull_request:
    types: [ opened, synchronize ]
permissions:
  issues: write
  pull-requests: write

env:
  POM_XML_DIRECTORY: '.'
  JAVA_VERSION: '17'
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  build-and-plan:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: 'Restore Project Dependencies Using Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.POM_XML_DIRECTORY }}'
          mvn clean package
          popd
        working-directory: java-functions

      - name: Terraform Setup and Plan
        id: terraform
        run: |
          terraform init
          terraform fmt
          terraform validate
          terraform plan -out tfplan
          terraform show -no-color tfplan | tee terraform-plan.txt
          terraform show -json tfplan > terraform-plan.json
#          terraform plan -no-color -out=plan-out -refresh-only > OUT
        working-directory: ./infrastructure
      - name: Use Plan
        run: echo "PLAN=$(cat ./infrastructure/terraform-plan.json)" >> $GITHUB_ENV
        shell: bash

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          plan: ${{ env.PLAN }}
          script: |
            const issue_number = context.issue.number;
            const repository = context.repo.repo;
            const owner = context.repo.owner;
            const plan = core.getInput('plan');
            const body = `Terraform Plan has been created. Please review the plan and approve the changes: ${ plan }`;
            
            github.rest.issues.createComment({
              issue_number: issue_number,
              owner: owner,
              repo: repository,
              body: body
            })
