name: Deploy Java project to Azure Function App

on:
  pull_request:
    types:
      - closed
env:
  AZURE_FUNCTIONAPP_NAME: 'm365-java-functions'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH_PS: 'powershell-functions'
  POM_XML_DIRECTORY: 'java-functions'        # set this to the directory which contains pom.xml file
  JAVA_VERSION: '17'                         # set this to the java version to use (e.g. '8', '11', '17')
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: 'Restore Project Dependencies Using Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.POM_XML_DIRECTORY }}'
          mvn clean package
          popd
      - name: 'Run Java Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.POM_XML_DIRECTORY }}'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          respect-pom-xml: true

      - name: 'Run Powershell Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa-powershell
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: powershell-functions/${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_PS }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
