name: Infrastructure Setup
on:
  push:
    branches:
      - 'main'
env:
  POM_XML_DIRECTORY: 'java-functions'
  JAVA_VERSION: '17'
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  setup-infrastructure-and-build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: 'Restore Project Dependencies Using Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.POM_XML_DIRECTORY }}'
          mvn clean package
          popd
        working-directory: java-functions

      - name: Terraform Init
        run: |
          terraform init
        working-directory: ./infrastructure

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan -refresh-only
        working-directory: ./infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./infrastructure
